---
title: "Jagdstrecke 2007 bis 2021"
output: github_document
---

```{r setup, echo=FALSE}
```

## Schwarzwild [^1]

[^1]: Quelle: F. Herrmann LJV-Thüringen

### Privatjagden

```{r Muffel, echo=FALSE}
x <- c(21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 09, 08, 07)
y <- c(29945, 32420, 37924, 23629, 34672, 24875, 25849, 21136, 19457, 31712, 16974, 23761, 16730, 25422, 18403 )
df1 <- data.frame(Jahr = x, Jagdstrecke = y)
df1

```

```{r echo=FALSE}
library(ggplot2)


ggplot(df1) +
  aes(y = Jagdstrecke,
      x = Jahr) +
  geom_point(shape = 21, size = 2, fill = "lightgreen") + 
  geom_smooth(formula = y ~ x, method = "loess", col='blue', linewidth=0.4,)
```

```{r echo=FALSE}
library(ggplot2)


ggplot(df1) +
  aes(y = Jagdstrecke,
      x = Jahr) +
  geom_point(shape = 21, size = 2, fill = "lightgreen") + 
  geom_smooth(formula = y ~ x, method = "lm", col='blue', linewidth=0.4,)
```

```{r pressure, echo=FALSE}
boxplot(df1$Jagdstrecke, col="green")


```

### Fiskus

```{r Schwarzwild, echo=FALSE}
x <- c(21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 09, 08, 07)
y <- c(5413, 6135, 7890, 5829, 7225, 6177, 5383, 4695, 3993, 5710, 4167, 3510, 3546, 4504, 3643)
df <- data.frame(Jahr = x, Strecke = y)
df

```

```{r echo=FALSE}
library(ggplot2)
ggplot(df) +
  aes(x=Jahr, 
      y=Strecke) +
    geom_point(shape = 21, size = 2, fill = "blue") +
    geom_smooth(formula = y ~ x, method = "loess", col='red', linewidth=0.4,)
```

```{r echo=FALSE}
library(ggplot2)


ggplot(df) +
  aes(y = Strecke,
      x = Jahr) +
  geom_point(shape = 21, size = 1, fill = "blue") +
  geom_smooth(formula = y ~ x, method = "lm", col='red', linewidth=0.4,)


```

```{r pressure1, echo=FALSE} 
boxplot(df$Strecke, col="blue")
```



```{r}
#| label: plot-penguins
#| warning: false
#| echo: false

ggplot(penguins, 
       aes(x = flipper_length_mm, y = bill_length_mm)) +
  geom_point(aes(color = species, shape = species)) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(
    title = "Flipper and bill length",
    subtitle = "Dimensions for penguins at Palmer Station LTER",
    x = "Flipper length (mm)", y = "Bill length (mm)",
    color = "Penguin species", shape = "Penguin species"
  ) +
  theme_minimal()
```
